AuthenticProducts/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AuthenticProducts.Models;

namespace AuthenticProducts.Controllers
{
    public class LoginController : Controller
    {
        AuthProductEntities db = new AuthProductEntities();
        // GET: Login
        public ActionResult Index()
        {
            LoginModel LogMod = new LoginModel();
            //LogMod.LoginUserTypes = db.UserTypes.Select(x => new SelectListItem { Text = x.UserTypeName, Value = x.UserTypeID.ToString() }).ToList();
            LogMod.LoginUserTypes = db.UserTypes.ToList();
            return View(LogMod);
        }

        [HttpPost]
        public ActionResult Autherize(LoginModel loginuser)
        {
            if (loginuser.UserTypeText == "admin")
            {
                var userDetail = db.Employees.FirstOrDefault(e => e.Employee_Name == loginuser.LoginUserName && e.Employee_Password == loginuser.LoginPassword);
                if (userDetail == null)
                {
                    loginuser.ErrorMessage = "Wrong User name or Password !!";
                    return View("Index", loginuser);
                }
                else
                {
                    UserControl.UserID = userDetail.Employee_ID;
                    UserControl.UserEmail = userDetail.Employee_email;
                    UserControl.UserName = userDetail.Employee_Name;
                    UserControl.UserTypeID = userDetail.Employee_Type_ID;
                    return RedirectToAction("Index", "Products");
                }
            }
            else if (loginuser.UserTypeText == "user")
            {
                var userDetail = db.Users.FirstOrDefault(u => u.UserName == loginuser.LoginUserName && u.UserPassword == loginuser.LoginPassword);
                if (userDetail == null)
                {
                    loginuser.ErrorMessage = "Wrong User name or Password !!";
                    return View("Index", loginuser);
                }
                else
                {
                    UserControl.UserID = userDetail.UserID;
                    UserControl.UserEmail = userDetail.UserEmail;
                    UserControl.UserName = userDetail.UserName;
                    UserControl.UserTypeID = 2;

                    return RedirectToAction("UserProdDetail", "Users", new {  });//id = userDetail.UserID
                }
            }
            else
            {
                loginuser.ErrorMessage = "User Type shoud be admin or user..";
                return View("Index", loginuser);
            }
            //return View();
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Login");
        }
    }
}

AuthenticProducts/Controllers/OpenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using AuthenticProducts.Models;

namespace AuthenticProducts.Controllers
{
    public class OpenController : Controller
    {
        AuthProductEntities db = new AuthProductEntities();
        // GET: Login
        public ActionResult Index()
        {
            ProductModel prod = new ProductModel();
            return View(prod);
        }

        [HttpPost]
        public ActionResult SerialSearch(ProductModel pr)
        {
            var Product = db.Products.FirstOrDefault(p => p.Serial_Num == pr.SerialNumber);
            if(Product == null)
            {
                pr.ErrorMessage = "Product Serial Number dose not exist..";
                return View("Index", pr);
            }
            else
            {
                var NoUser = db.Users.FirstOrDefault(u => u.UserID == 5);
                UserControl.UserID = NoUser.UserID;
                UserControl.UserEmail = NoUser.UserEmail;
                UserControl.UserName = NoUser.UserName;
                UserControl.UserTypeID = 2;

                return RedirectToAction("DirectClaim", "ClaimProduct", new { ProdId = Product.Product_ID });
                //return RedirectToAction("Details", "Products", new { Prodid = ProductID, _isDirectClaim = 1 });
            }
            //return View();
        }
    }
}

AuthenticProducts/Views/Login/Index.cshtml
@using AuthenticProducts.Models
@model  AuthenticProducts.Models.LoginModel
    
@{
    ViewBag.Title = "Login"; 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <style>
        #login_div{
            position: absolute;
            left: 40%;
            top:40%;
            border: 1px solid #ccc;
            padding: 10px 10px;
        }
        .field-validation-error{
            color:red;
        }
    </style>
</head>
<body>
    <div id="login_div">
        @using (Html.BeginForm("Autherize", "Login", FormMethod.Post))
        {
        <table>
            <tr>
                <td></td>
                <td style="text-decoration:underline">Authentic Product</td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.LoginUserName)
                </td>
                <td>
                    @Html.EditorFor(model => model.LoginUserName)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ValidationMessageFor(model => model.LoginUserName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.LoginPassword)
                </td>
                <td>
                    @Html.EditorFor(model => model.LoginPassword)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ValidationMessageFor(model => model.LoginPassword)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(model => model.UserTypeText)
                </td>
                <td>
                    <select id="UserTypeText" name="UserTypeText">
                        <option value="admin">admin</option>
                        <option value="user">user</option>
                    </select>
                    @*@Html.EditorFor(model => model.UserTypeText)*@
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ValidationMessageFor(model => model.UserTypeText)
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <label class="field-validation-error">
                        @Html.DisplayFor(model => model.ErrorMessage)
                    </label>
                </td>
            </tr>

            <tr>
                <td></td>
                <td>
                    <input type="Submit" name="name" value="Login" />
                    <input type="Submit" name="name" value="Clear" />
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    @Html.ActionLink("Go To Direct Claim", "Index", "Open", new { }, null)
                </td>
            </tr>
        </table>
        }
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

AuthenticProducts/Views/Login/Logout.cshtml
@{
    ViewBag.Title = "LogOut"; 
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Logout</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>